Fix missing ghost.fullname in template call. (#4611)
* Fix missing ghost.fullname in template call.

Given I am a user of this chart,
When I try to deploy this using serviceType NodePort,
Then helm will explode and tell me that 

```
Error: render error in "ghost/templates/NOTES.txt": template: ghost/templates/NOTES.txt:39:130: executing "ghost/templates/NOTES.txt" at <{{template "fullname...>: template "fullname" not defined
```

* Bump ghost chart version number.

* Bump ghost chart version number.

* Bump chart version number.